//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int idOrder { get; set; }
        public string hoTen { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> ngayDen { get; set; }
        public Nullable<System.DateTime> ngayDi { get; set; }
        public Nullable<int> soPhong { get; set; }
        public Nullable<int> nguoiLon { get; set; }
        public Nullable<int> treEm { get; set; }
        public Nullable<int> @checked { get; set; }
    }
}
